### ISSUE TITLE
Approve and Publish OSLC RM v2.1 PS01 (SMV)

### ISSUE THREAD

**Issue by berezovskyi** [oasis-open-projects/administration#12]
*Requester name:* Andrew Berezovskyi

*OP name:* OSLC OP

*OP mailing address:* oslc-op@lists.oasis-open-projects.org

*Title:* OSLC Requirements Management Version 2.1 Project Specification 01

*Approval link:* 
https://lists.oasis-open-projects.org/g/oslc-op/message/320

*Notes:* 
The publication date in the generated materials is set to 2020-09-03.

**Comment by OASIS-OP-Admin** [comment]
Andrew, making sure I have this correct: this is not the request to publish yet but rather the request to hold the Special Majority Vote to approve publishing. Have I got that right?

**Comment by berezovskyi** [comment]
Yes, correct. I was expecting we will handle both of those things in a single issue?

cc @jadelkhoury as the spec editor.

**Comment by OASIS-OP-Admin** [comment]
OK, thanks for clarifying for me. So I will add a note to my calendar to have the ballot open 8/27 and close 9/3.

**Comment by OASIS-OP-Admin** [comment]
Poll is set up. See https://lists.oasis-open-projects.org/g/oslc-op-pgb/topic/vote_on_oslc_requirements/76430414?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,76430414

Poll closes on Sept. 3

**Comment by berezovskyi** [comment]
@OASIS-OP-Admin have you determined if the vote has passed? Thank you!

**Comment by OASIS-OP-Admin** [comment]
You have 3 affirmative votes so the ballot has passed. I will close it tomorrow and start work on publishing the PS.

**Comment by OASIS-OP-Admin** [comment]
The Special Majority Vote to approve Requirements Management as a Project Specification has closed and passed. 3 of 4 eligible voters cast affirmative votes. No negative votes were cast. See the ballot at https://lists.oasis-open-projects.org/g/oslc-op-pgb/topic/vote_on_oslc_requirements/76430414?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,76430414

OASIS staff will now publish and announce the PS. Let us know if you have any questions. 

And of course, congratulations on producing the 2nd Project Specification from the OASIS Open Projects program.

**Comment by berezovskyi** [comment]
@paul-knight hello, did you have a chance to review the package?

**Comment by paul-knight** [comment]
initial review underway...

**Comment by paul-knight** [comment]
Review notes:
- Two TTL files - show copyright year as 2019. Not a problem, but should be updated to 2020 for next publication.

Part 1: Specification
- URI for "Latest stage" PDF is set to be the HTML instead of the PDF format. (This occurs in all three Parts) I will fix that and continue with publication, unless other blocking issues are noted. 
- In the list of Additional components, the use of "Part 4" and "Part 5" for the two TTL files is not recommended,  especially since it does not match the internally-declared names "OSLC Requirements Management (RM) Vocabulary" and "OSLC Requirements Management (RM) Resource Shape Constraints". For consistency, it would be good to use matching names. (not a blocking issue).

Part 2: Vocabulary
- no additional issues noted

Part 3: Constraints
- Note this is a new Part since PSD02 - I will need to add a new pair of symlinks during installation (reminder)
- No other issues noted

I have fixed the hyperlinks for the "Latest stage" PDFs.
I'll proceed with publication, although I'll also review the other open documents so they can be fixed by the Editors if needed.

Link check shows no unexpected broken links - all References good!

Note: wide tables in some Parts may result in the use of small fonts when generating the PDF formats.

Looks good!

**Comment by paul-knight** [comment]
Noted that Part 2 had empty "Previous stage" - fixed using the links for PSD02.

**Comment by paul-knight** [comment]
@berezovskyi : files to be published are attached in ZIP file
[rm-v2.1-ps01-staging1.zip](https://github.com/oasis-open-projects/administration/files/5295459/rm-v2.1-ps01-staging1.zip)

Generated PDF files.
- reviewed three possible PDF generation approaches described in https://github.com/oasis-open-projects/administration/issues/11
- created the PDFs by temporarily installing the three HTML files into their expected locations in https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/, then referencing those FQDN addresses in the WKHTMLTOPDF command line.
- note since there are no additional images beyond the logo, I did not need to copy those elements to docs.oasis-open-projects.org (OASIS OP Library) - normally that would be necessary

After generating and inspecting PDFs, removed the files and directory in OASIS OP Library, and continued with typical install process for staging review.

Requested OASIS staff staging review:

Please review the staging server installation of the files for OSLC RM v2.1 PS01.

This has three parts, but no images.
I generated the PDF by temporarily stuffing the three HTML files into the OASIS-OP Library, referencing them from WKHTMLTOPDF to make the PDFs, then removing the temporary directory and files. Please check the inter-Part links in the PDFs - they seem okay to me.

The files are:

OSLC Requirements Management Version 2.1
Project Specification 01
03 September 2020

OSLC Requirements Management Version 2.1. Part 1: Specification
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/rm/v2.1/ps01/requirements-management-spec.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/rm/v2.1/ps01/requirements-management-spec.pdf
OSLC Requirements Management Version 2.1. Part 2: Vocabulary
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/rm/v2.1/ps01/requirements-management-vocab.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/rm/v2.1/ps01/requirements-management-vocab.pdf
OSLC Requirements Management Version 2.1. Part 3: Constraints
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/rm/v2.1/ps01/requirements-management-shapes.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/rm/v2.1/ps01/requirements-management-shapes.pdf
Turtle files:
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/rm/v2.1/ps01/requirements-management-shapes.ttl
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/rm/v2.1/ps01/requirements-management-vocab.ttl

Please add comments to https://github.com/oasis-open-projects/administration/issues/12.
(This is also tracked in https://issues.oasis-open.org/browse/TCADMIN-3798.)

**Comment by OASIS-OP-Admin** [comment]
Everything looks good to me. I reviewed the documents and I approve promoting them to docs.oasis-open-projects.org

**Comment by paul-knight** [comment]
To be promoted to docs.oasis-open-projects.org along with other concurrent OSLC-OP documents.

**Comment by paul-knight** [comment]
I found some significant issues in the PDF files which (I think) can be fixed by manually editing each PDF (14 of them across the four PS01s) and re-installing. However, I'll go ahead and ask for a sanity check on the documents, so if anything else shows up, I can also address that, while fixing the PDFs.

Essentially, the WKHTMLTOPDF process does not handle a self-referential link in the base HTML the way we want it to.
It changes the self-referential link in the HTML to a self-referential link within the PDF. This means that it turns the "This stage/version" link for HTML into a link for the PDF (and also any other self-referential links, like the citation format).

Otherwise, I think these are ready to release - so here is the request for a sanity check, while I get the 14 files patched up...
The files are:

OSLC Requirements Management Version 2.1
Project Specification 01
03 September 2020

OSLC Requirements Management Version 2.1. Part 1: Specification
https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-spec.html
https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-spec.pdf
OSLC Requirements Management Version 2.1. Part 2: Vocabulary
https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-vocab.html
https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-vocab.pdf
OSLC Requirements Management Version 2.1. Part 3: Constraints
https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-shapes.html
https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-shapes.pdf
Requirements Management Vocabulary definitions file: https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-vocab.ttl
Requirements Management Resource Shape Constraints definitions file: https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-shapes.ttl

**Comment by OASIS-OP-Admin** [comment]
Copyright date in the ttl files is still 2019. Otherwise these all look ready to go. With the fixes you are making, I approve to release.

**Comment by paul-knight** [comment]
Fixed the copyright dates for the turtle files (changed to 2020).

**Comment by paul-knight** [comment]
NEW, improved PDFs completed, and ready for loading.

**Comment by paul-knight** [comment]
Files repackaged, with ZIP and manifest files, dates set, etc.
Removed README warning file.
Should be ready for release along with other three (AM will be handled separately later - waiting for updated files).

**Comment by paul-knight** [comment]
@chet-ensign Chet will coordinate announcements of the four Project Specifications (Core, CM, RM, Query)

Note the publication URIs are listed in an earlier comment.

**Comment by OASIS-OP-Admin** [comment]
I have announced the publication of the Prj Specs - OASIS homepage (https://www.oasis-open.org/news/announcements/four-new-project-specifications-approved-by-the-oslc-open-project), Twitter, LinkedIn groups, emails (https://lists.oasis-open-projects.org/g/oslc-op/topic/four_new_project/77486324?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,77486324). I also added them to the OASIS Standards page under the Committee/Project Specifications grouping (https://www.oasis-open.org/standards#oslc-rm-v2.1-ps01). I'm checking with Andrew about adding this as a news article to open-services.net. 

No further tasks to do so I'm closing this ticket.
