### ISSUE TITLE
SMV for OSLC Core v3.0 PS01

### ISSUE THREAD

**Issue by berezovskyi** [oasis-open-projects/administration#14]
*Requester name:* Andrew Berezovskyi	

*OP name:* OSLC OP

*OP mailing **address:*** oslc-op@lists.oasis-open-projects.org

*Title:* OSLC Core v3.0 Project Specification 01

*Approval link:* 
https://lists.oasis-open-projects.org/g/oslc-op/topic/oslc_core_v3_0_ps_01_notice/76458174?p=,,,50,0,0,0::recentpostdate%2Fsticky,,,50,2,0,76458174

*Notes:* 
Requesting to open a ballot on September 10

**Comment by chet-ensign** [comment]
Acknowledged. Dates for the ballot have been added to my calendar.

**Comment by berezovskyi** [comment]
@OASIS-OP-Admin is it possible to do pre-publication review for the package in parallel, please? We have not received any critical feedback so far. Plus, this spec has many parts.

**Comment by OASIS-OP-Admin** [comment]
The Special Majority Vote is set up. See https://lists.oasis-open-projects.org/g/oslc-op-pgb/topic/vote_on_oslc_core_v3_0_1/76734933?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,76734933

Poll closes on Sept. 16 at which point we will announce the results and proceed with the next steps.

**Comment by OASIS-OP-Admin** [comment]
The ballot closed and passed. OSLC Core received 4 yes votes, no no votes, and no abstentions. The result was announced to the PGB and the project mailing list. See https://lists.oasis-open-projects.org/g/oslc-op-pgb/topic/oslc_core_v3_0_and_change/76910221?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,76910221

Staff will now publish the PS and notify the project when it is available.

**Comment by OASIS-OP-Admin** [comment]
TC Admin JIRA ticket https://issues.oasis-open.org/browse/TCADMIN-3806 opened to track this.

**Comment by paul-knight** [comment]
Review of files in ZIP file:
- https://github.com/oslc-op/oslc-specs/releases/download/untagged-31a2b7cea0a5b7019940/core-v3.0-ps01.zip

- "Previous stage" should refer to the PSD04 files instead of the old TC material (also, bad PDF link) - fixed for parts:
-- attachments
-- core-vocab
-- dialogs
-- discovery
-- oslc-core
-- resource-preview
-- resource-shape

- Part 8 (core-shapes) is new for PS01
-- fixed "Latest stage" PDF hyperlink
-- will need to add new symlink during publication (reminder for Paul)

The two TTL files have copyright year set to 2020.

There are two subdirectories, /contexts and /schema, each with one file. These are not listed in "Additional components", but the files are apparently the ones discussed in Part 3: Resource Preview, Appendix A (apparently, the material listed in Examples 20 and 21). However, there seems to be no reference to their presence and no link to the accompanying files.
- for future publications, these should be listed as "Additional components", and they should be linked in some way to the specifications.
- TC Process requires:
_All normative computer language definitions must also be provided in separate plain text files;
Each text file must be referenced from the Work Product; and
Where any definition in these separate files disagrees with the definition found in the specification documentation, the definition in the separate file prevails_.
- Appendix A states that these are not normative, but it would be helpful to readers to provide the links from the text, and references in "Additional components"

With the fixes in place, this looks ready for next publication steps.
NOTE: need to inspect PDF files while generating them, for possible image overflows  (reminder for Paul)

**Comment by paul-knight** [comment]
Links to OSLC-Query (core-21) in OSLC Core 4.1.9 and 4.3 need further investigation - to see if they will work after installation.
In Part 4: Delegated Dialogs, the link to OWASP Clickjacking at the end of 3.4 should be in the References section. (Informative).

**Comment by paul-knight** [comment]
links for OSLC Query use href="../query/oslc-query.html"
source of reference will be https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/oslc-core.html

It appears that these links will point to https://docs.oasis-open-projects.org/oslc-op/core/v3.0/query/oslc-query.html, and **will fail**.

The target should be (if using "Latest stage") https://docs.oasis-open-projects.org/oslc-op/query/v3.0/oslc-query.html

So it appears that the links SHOULD be:
- href="../../../query/v3.0/oslc-query.html"

Actually, the recommended approach is to place an entry in References, then cite that, especially since the link is to the document as a whole. NOTE: there is a reference to [OSLCQuery3], but it appears to be broken (http://open-services.net/specifications/query/oslc-query.html), and probably should point to the OSLC-OP link noted above (https://docs.oasis-open-projects.org/oslc-op/query/v3.0/oslc-query.html).

I will not try to adjust this. However, it will need to be fixed before this can became an OASIS Standard (future).

**Comment by berezovskyi** [comment]
Thank you, Paul, I agree with you that a reference to Query shall be absolute.

--  
Andrew

**Comment by paul-knight** [comment]
quick review of PDFs generated locally - for image or overflow issues

- [x] resource-shape

- [x] resource-preview

- [x] oslc-core

- [x] discovery

- [x] dialogs

- [x] core-vocab

- [x] core-shapes

- [x] attachments

No issues noted

**Comment by paul-knight** [comment]
Generated PDF files after loading the HTML and /images temporarily into OASIS Library.
All except oslc-core generated successfully, but there were persistent image timeouts/drops with oslc-core. (This is strange - there are only three images, and it failed with two of them.)
Apparently, this is a known problem - https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3715.

Possible work-arounds:
1) embed some of the images into the HTML code as base64 encoded images. (new process for me)
2) create temporary HTML file  replacing the relative links with FQDN links. (I've done this, for QM - https://github.com/oasis-open-projects/administration/issues/11)
3) create temporary HTML file to load to OASIS Library which references some of the image files locally. That is, replace some of the larger image file references in the HTML, to point to a local instance using a path like: file:///C:/Users/Paul/Documents/OASIS/OASIS-OPs/OSLC/core-v3.0/ps01/extra/images/oslc-architecture.png - DOES NOT WORK in this case.
4) It seems that the problem starts with the logo, so I copied the logo into the /images directory, modified the HTML to use that, and it WORKED. This is strange, since none of the other parts had trouble with the logo. I could not detect any difference in the links for the logo, compared to another part that worked with no issues.
(working assumption - the time delay of negotiating https for the logo file, along with the fairly large second image (oslc-architecture.png = 239K) triggered the time-out issue, and both were dropped)

All eight PDF files now look okay, with proper resolutions for the relative links.

**Comment by paul-knight** [comment]
NOTE - the reason for generating the PDFs from the HTMLs and images after temporarily installing them in the target directory (docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/) is to cause the relative links in the PDFs to resolve properly (after they are installed into the target directory). The WKHTMLTOPDF software is not able to generate PDFs with actual relative links - they are all FQDN.

**Comment by paul-knight** [comment]
Prepared installation scripts and support files for staging process.

**Comment by paul-knight** [comment]
on the WKHTMLTOPDF image issue, I also found https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4044, which links image issues to using HTTPS, and indicates that a later version of the software may overcome this.
Current: 12.5
later: 13.0
I'll check this if problem shows up again (not needed right now - PDFs all generated).

**Comment by paul-knight** [comment]
Staged files - reviewing.

Part 1 - As noted earlier, the links (in oslc-query.html, sections 4.1.9 and 4.3) for OSLC Query are broken/malformed.

I did not note any other issues now - final link check (sanity check) after installation needed to verify the inter-Part links.

**Comment by paul-knight** [comment]
Requested OASIS staff staging review: (ZIP of files also attached)
[core-v3.0-ps01-staging.zip](https://github.com/oasis-open-projects/administration/files/5308248/core-v3.0-ps01-staging.zip)

Please review the OP staging server installation of the files for OSLC Core v3.0 PS01.

This consists of eight parts (HTML and PDF) and two turtle (.ttl) files. (These are currently listed as Parts 9 and 10.)
There are also two subdirectories (/context and /schema), each with one "machine-readable" file. These are not explicitly referenced from any of the prose documents, although they appear to be the material listed in Examples 20 and 21 in Appendix A of Part 3: Resource Preview.

I noted one broken link in Part 1 (oslc-query.html), section 4.1.9, which is repeated in section 4.3, but did not note any other issues.

The files are:

OSLC Core Version 3.0
Project Specification 01
17 September 2020

OSLC Core Version 3.0. Part 1: Overview
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/oslc-core.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/oslc-core.pdf
OSLC Core Version 3.0. Part 2: Discovery
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/discovery.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/discovery.pdf
OSLC Core Version 3.0. Part 3: Resource Preview
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/resource-preview.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/resource-preview.pdf
OSLC Core Version 3.0. Part 4: Delegated Dialogs
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/dialogs.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/dialogs.pdf
OSLC Core Version 3.0. Part 5: Attachments
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/attachments.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/attachments.pdf
OSLC Core Version 3.0. Part 6: Resource Shape
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/resource-shape.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/resource-shape.pdf
OSLC Core Version 3.0. Part 7: Vocabulary
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/core-vocab.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/core-vocab.pdf
OSLC Core Version 3.0. Part 8: Constraints
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/core-shapes.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/core-shapes.pdf
OSLC Core Vocabulary definitions file: https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/core-vocab.ttl
OSLC Core Resource Shape Constraints definitions file: https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/ps01/core-shapes.ttl

Please add comments to https://github.com/oasis-open-projects/administration/issues/14.
This issue is also tracked in https://issues.oasis-open.org/browse/TCADMIN-3806.

**Comment by OASIS-OP-Admin** [comment]
I reviewed the files. Big production! Everything looks good to me. I approve to promote to docs.oasis-open-projects.org.

**Comment by paul-knight** [comment]
Files in place in OASIS-OP Library (docs-oasis-open-projects.org) along with three others. (CM, Query, RM)
I've completed review of the files in OSLC-Core (all good) - will start final "sanity check" after checking the others.

**Comment by paul-knight** [comment]
Noted one minor unwanted artifact in almost all of the PDF files:
- each instance of a hyperlink to the HTML format of that Part within the PDF is changed to purple instead of blue (indicating it has been visited). So Part 1 PDF always shows Part 1 HTML as "visited", etc.
- This shows up in three places (This stage, Additional components (this document), Citation format)
- This occurs only when generating the PDF after temporarily installing the HTML (to set relative links properly). It does not occur with "Query", which does not have any relative links and had the PDF generated locally.
- As far as I can tell, this is an unavoidable artifact, since the WKHTMLTOPDF process must "visit" the temporarily-installed HTML in order to turn it into PDF.
- This is not a blocking issue - no action needed.

**Comment by paul-knight** [comment]
Yikes - just discovered on further investigation that what I thought were just "visited" links are actually somewhat corrupted - instead of actually pointing to the HTML, they point to the same PDF, using a hyperlink which consists of the PDF 's own hyperlink, with the HTML hyperlink appended after a hash (#) sign.
- instead of https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-shapes.html the actual hyperlink is https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/requirements-management-shapes.pdf#https%3A//docs.oasis-open-projects.org/oslc-op/rm/v2.1/ps01/requirements-management-shapes.html
- when clicked, the links just jump to the middle of the same PDF document, instead of to the HTML.
- This is something which will need to be avoided for future publications, at the least. However, it may be acceptable for one instance here, to avoid delay in publication

**Comment by paul-knight** [comment]
I found some significant issues in the PDF files which (I think) can be fixed by manually editing each PDF (17 of them across the four PS01s) and re-installing. However, I'll go ahead and ask for a sanity check on the documents, so if anything else shows up, I can also address that, while fixing the PDFs.

Essentially, the WKHTMLTOPDF process does not handle a self-referential link in the base HTML the way we want it to.
It changes the self-referential link in the HTML to a self-referential link within the PDF. This means that it turns the "This stage/version" link for HTML into a link for the PDF (and also any other self-referential links, like the citation format).

Otherwise, I think these are ready to release - so here is the request for a sanity check, while I get the 17 files patched up...
The files are:

OSLC Core Version 3.0
Project Specification 01
17 September 2020

OSLC Core Version 3.0. Part 1: Overview
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/oslc-core.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/oslc-core.pdf
OSLC Core Version 3.0. Part 2: Discovery
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/discovery.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/discovery.pdf
OSLC Core Version 3.0. Part 3: Resource Preview
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/resource-preview.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/resource-preview.pdf
OSLC Core Version 3.0. Part 4: Delegated Dialogs
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/dialogs.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/dialogs.pdf
OSLC Core Version 3.0. Part 5: Attachments
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/attachments.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/attachments.pdf
OSLC Core Version 3.0. Part 6: Resource Shape
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/resource-shape.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/resource-shape.pdf
OSLC Core Version 3.0. Part 7: Vocabulary
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/core-vocab.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/core-vocab.pdf
OSLC Core Version 3.0. Part 8: Constraints
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/core-shapes.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/core-shapes.pdf
OSLC Core Vocabulary definitions file: https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/core-vocab.ttl
OSLC Core Resource Shape Constraints definitions file: https://docs.oasis-open-projects.org/oslc-op/core/v3.0/ps01/core-shapes.ttl

**Comment by OASIS-OP-Admin** [comment]
Everything looks good to me. With the PDF fixes, I approve to release.

**Comment by paul-knight** [comment]
Attaching the fixed PDFs in a ZIP file for review, if wanted - 
[core-v3.0-PDFs-final.zip](https://github.com/oasis-open-projects/administration/files/5343356/core-v3.0-PDFs-final.zip)

After I finish the PDFs for Resource Management, I'll get all 4 re-installed for sanity check.

**Comment by paul-knight** [comment]
NEW, improved PDFs completed, and ready for loading.

**Comment by paul-knight** [comment]
Files repackaged, with ZIP and manifest files, dates set, etc.
Removed README warning file.
Should be ready for release along with other three (AM will be handled separately later - waiting for updated files).

**Comment by paul-knight** [comment]
@chet-ensign Chet will coordinate announcements of the four Project Specifications (Core, CM, RM, Query)

Note the publication URIs are listed in an earlier comment.

**Comment by OASIS-OP-Admin** [comment]
I have announced the publication of the Prj Specs - OASIS homepage (https://www.oasis-open.org/news/announcements/four-new-project-specifications-approved-by-the-oslc-open-project), Twitter, LinkedIn groups, emails (https://lists.oasis-open-projects.org/g/oslc-op/topic/four_new_project/77486324?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,77486324). I also added them to the OASIS Standards page under the Committee/Project Specifications grouping (https://www.oasis-open.org/standards#oslc-core-v3.0-ps01). I'm checking with Andrew about adding this as a news article to open-services.net. 

No further tasks to do so I'm closing this ticket.
