### ISSUE TITLE
Request to Publish OSLC Core 3.0 PSD04

### ISSUE THREAD

**Issue by jamsden** [oasis-open-projects/administration#9]
*Requester name:* Jim Amsden

*OP name:*  OASIS OSLC OP

*OP email address:* oslc-op@lists.oasis-open-projects.org 

*Title:* OSLC Core Version 3.0. Part 1: Overview
(part 1 of 7 parts)

*Request link:* 
https://github.com/oslc-op/oslc-specs/releases/tag/untagged-be44e9a6c33030d6c6a8 (see the ZIP file attached to the draft release)

*Notes:*

**Comment by OASIS-OP-Admin** [comment]
@paul-knight , I am assigning the next OSLC PSD over to you. - @chet-ensign

**Comment by paul-knight** [comment]
downloaded source material from:
https://github.com/oslc-op/oslc-specs/releases/download/untagged-be44e9a6c33030d6c6a8/Core-v3.0-PSD-4-20191220.zip

setting up scripts and file structures to publish the seven parts...

**Comment by paul-knight** [comment]
Inspected files.
- 2 JSON files in /contexts and /schema
- 20 .ttl files in /shapes and /vocab
- none of the files need copyright blocks
- none of the files are listed in "Additional components" (difference from other OSLC Work Products)
- no unexpected broken links noted in .html files yet

- 7 main specification .html files, with a directory of images

attachments.html (part 5) and core-vocab.html (part 7) contain doubled horizontal lines (\<hr> tags) just before Section 1.
resource-shape.html (Part 6) contains tripled lines before Section 5.
- removed the duplicates, to avoid having blank pages in the PDF files.
- these elements should be noted for fixes in future publications

Prepared the scripts and generated PDF versions of each of the .html files.

Looks ready for staging installation and review (likely tomorrow).

**Comment by paul-knight** [comment]
Added meta description tags (using text from the "Abstract" sections) to the HTML files for each of the seven parts:
Part 1 (oslc-core)
\<meta name="description" content="This specification defines the overall approach to Open Services for Lifecycle Collaboration (OSLC) based specifications.">
Part 2 (discovery)
\<meta name="description" content="This specification outlines a common approach for HTTP/LDP-based servers to be able to publish their RESTful API capabilities and how clients discover and use them.">
Part 3 (resource-preview)
\<meta name="description" content="This document defines a technique to get a minimal HTML representation of a resource identified by a URL.">
Part 4 (dialogs)
\<meta name="description" content="This document defines delegated dialogs, which allow one application to embed a creation or selection UI into another using HTML and JavaScript.">
Part 5 (attachments)
\<meta name="description" content="This document describes a minimal way to manage attachments related to web resource.">
Part 6 (resource-shape)
\<meta name="description" content="This document defines a high-level RDF vocabulary for specifying the shape of RDF resources.">
Part 7 (core-vocab)
\<meta name="description" content="This document defines the OSLC Core RDF vocabulary terms and resources.">

Set up base-tagged versions of the seven parts (to handle relative references when the HTML files are dereferenced using the "Latest stage" links).

Set up installation scripts.

**Comment by paul-knight** [comment]
During staging, noted a couple of items for possible revision in future stages:
- In oslc-core (Part 1), noted that about 12 references to other Parts in the Conformance section (Section 6) refer specifically to the csprd03 publication, rather than to the current stage (i.e., they don't use relative links). See CORE-40 through -45, plus six instances in the text above the conformance table itself. (add to issues for next stage)
- In resource-preview (Part 3), conformance clause RP-22 refers to "XML Representation Format". Although this is hyperlinked to a resource on open-services.net, note that Appendix B is entitled "XML Representation Format", so this may be ambiguous. (possible issue)

**Comment by paul-knight** [comment]
Initiated OASIS staff staging review:
- prepared files with timestamps, ZIP, and manifest in personal directory
- staging directory in place (due to concurrent work on qm-v2.1-psd02 - see https://github.com/oasis-open-projects/administration/issues/8)
- created Work Product, Version, and stage directories
- copied files into stage directory
- added new symlinks (14)
- installed README warning file
- set timestamps for directory and symlinks, also for WP and version directory.
- checked installation
- requested OASIS staff staging review:

Please review the OP staging server installation of the files for OSLC Core 3.0 PSD04.

This consists of seven parts, plus several directories of related files (none mentioned in "Additional components").
Since these are .ttl files, JSON schemas, and image files, I did not add stage-specific copyright blocks to any of these files.
I added the expected meta "description" tags to the seven HTML files, and listed the tag text in the github ticket so they can be incorporated by the OSLC Editors in future stages if desired.

The files are:

OSLC Core Version 3.0
Project Specification Draft 04
20 December 2019

OSLC Core Version 3.0. Part 1: Overview
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/oslc-core.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/oslc-core.pdf
OSLC Core Version 3.0. Part 2: Discovery
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/discovery.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/discovery.pdf
OSLC Core Version 3.0. Part 3: Resource Preview
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/resource-preview.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/resource-preview.pdf
OSLC Core Version 3.0. Part 4: Delegated Dialogs
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/dialogs.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/dialogs.pdf
OSLC Core Version 3.0. Part 5: Attachments
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/attachments.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/attachments.pdf
OSLC Core Version 3.0. Part 6: Resource Shape
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/resource-shape.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/resource-shape.pdf
OSLC Core Version 3.0. Part 7: Vocabulary
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/core-vocab.html
https://docs-staging.oasis-open-projects.org/ztest/oslc-op/core/v3.0/psd04/core-vocab.pdf

Please add comments to https://github.com/oasis-open-projects/administration/issues/9.

**Comment by OASIS-OP-Admin** [comment]
I checked over the files. Everything looks good to go. I approve to promote to docs.oasis-open-projects.org

**Comment by paul-knight** [comment]
- Synced files from /ztest to canonical directory (/htdocs)
- Synced to OP Library (docs.oasis-open-projects.org)
- checked links, etc.
-- no unexpected broken links in part 1, part 2, part 3, part 4, part 5, part 6, or part 7
-- Part 6 has directly linked references to other specifications (e.g., RDF and XML Schema cited in conformance clause RS-21) which should probably be handled as citations of References.
-- the document retrieved at the namespace URI (http://open-services.net/ns/core#) appears to be out of date.
- requested sanity check:

Please review the OASIS OP Library installation of the files for OSLC Core 3.0 PSD04.
I did not see any publication-related issues, although I noted a few editorial suggestions in the ticket.

The files are:

OSLC Core Version 3.0
Project Specification Draft 04
20 December 2019

OSLC Core Version 3.0. Part 1: Overview
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/oslc-core.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/oslc-core.pdf
OSLC Core Version 3.0. Part 2: Discovery
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/discovery.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/discovery.pdf
OSLC Core Version 3.0. Part 3: Resource Preview
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/resource-preview.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/resource-preview.pdf
OSLC Core Version 3.0. Part 4: Delegated Dialogs
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/dialogs.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/dialogs.pdf
OSLC Core Version 3.0. Part 5: Attachments
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/attachments.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/attachments.pdf
OSLC Core Version 3.0. Part 6: Resource Shape
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/resource-shape.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/resource-shape.pdf
OSLC Core Version 3.0. Part 7: Vocabulary
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/core-vocab.html
https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/core-vocab.pdf

Please add comments to https://github.com/oasis-open-projects/administration/issues/9.

**Comment by OASIS-OP-Admin** [comment]
The files look good to me. I approve to release.

**Comment by paul-knight** [comment]
- Removed README warning file and reset directory timestamp in canonical directory on staging server.
- synced to OP Library (docs.oasis-open-projects.org)

Files available for public access in OASIS OP Library.

Sent out announcement message to:
- oslc-op@lists.oasis-open-projects.org

- email: https://lists.oasis-open-projects.org/g/oslc-op/message/218

**Comment by paul-knight** [comment]
We're all done with publication process now - this issue can be closed.

**Comment by OASIS-OP-Admin** [comment]
Closing this issue
